### ISSUE TITLE
Scenario editor: checklist

### ISSUE THREAD

**Issue by breznak** [breznak/openDS#3]
This is a fully automated scenario editor, that lets the experiment designer choose which elements and how often (probability) will appear: these will then be automatically generated along the street as the user drives. 

E.g.: Pedestrian density 1%, falling boxes 10%, etc.

TODO: 
- [x] implement function `put(object, posX, posY)`
  - [ ] ask devs if there's a better way than editing the XML files
- [x] menu "Welcome screen" with
  - [x] check-list of distractors to use
  - [x] slider/num input to set probability of each distraction
- [x] implement function `generateRandomDistractor(listDistractorObjects[], listDistractorProbabilities[], listAheadDistance[], time computeEveryNth)`
  - that is called during the drive (each Nth "time")
  - samples distractors and generates them on/along the road

**Comment by JohnnyMarek** [comment]
Function is mostly prepared, waiting just for advice from original developers.

**Comment by breznak** [comment]
will be implemented in #15
